Wirelength Analyzer (#25)
* add wirelength analyzer

- add documentation about how wirelength scores are computed
- add wa.py -- reference implementation of wirelength analyzer
- add tests/test infra for wa.py

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* GitHub Actions to archive *.wirelength logs

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Switch to setup-wirelength_analyzer target

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* first pass at github action to run wirelength analyzer unit tests

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* add pipe for multi-line command

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* setup wirelength analyzer first

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* Verify existence of wirelength

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Add WIRELENGTH_ANALYZER_MOCK_RESULT to make workflow

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Missing backslash

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Tidy up

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Allow wirelength grep to fail if nxroute

Since there may be no paths inside the nxroute window

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Rename job

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* stop warning on every net with stubs and count instead

* Check sources/stubs, improve mock result warning

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Fix make.yml

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* wirelength_analyzer testing to print test

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Missing files

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Escape grep +

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Do not expect stubs for koios

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* update root README to refer to wirelength analyzer

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* Consistent terminology

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Link to say critical-path wirelength

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Update compute-score.py to include critical-path-wirelength

also add better table formatting

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* update compute-score item in contest description to reference wirelength

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* update compute-score to use floats internally

fixes error with mock wirelength analyzer results

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* Update flow-detailed.png

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Restore RapidWright submodule

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* update help text for mode option of wa.py

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* Fix typos

Co-authored-by: Chris Lavin <chris.lavin@amd.com>

* minor re-wording in README for wa.py

also update help text for verbosity in wa.py

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>

* Fix argparse formatting

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Restore RapidWright submodule

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

* Specify default mode

Signed-off-by: Eddie Hung <eddie.hung@amd.com>

---------

Signed-off-by: Zak Nafziger <zak.nafziger@amd.com>
Signed-off-by: Eddie Hung <eddie.hung@amd.com>
Co-authored-by: Eddie Hung <eddie.hung@amd.com>
Co-authored-by: Chris Lavin <chris.lavin@amd.com>

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -54,7 +54,10 @@ jobs:
       - env:
           REPORT_ROUTE_STATUS_URL:      ${{ secrets.REPORT_ROUTE_STATUS_URL }}
           REPORT_ROUTE_STATUS_AUTH:     ${{ secrets.REPORT_ROUTE_STATUS_AUTH }}
+          # With no access to Vivado, assume that CheckPhysNetlist always returns a PASS for all routers except for nxroute-poc
           CHECK_PHYS_NETLIST_MOCK_PASS: ${{ matrix.router != 'nxroute-poc' && secrets.REPORT_ROUTE_STATUS_URL == '' }}
+          # For certain benchmarks, wirelength_analyzer requires more memory than that available in GitHub Actions
+          WIRELENGTH_ANALYZER_MOCK_RESULT: ${{ matrix.benchmark == 'koios_dla_like_large' }}
         run: |
           make ROUTER="${{ matrix.router }}" BENCHMARKS="${{ matrix.benchmark }}" VERBOSE=1
       - name: Score summary
@@ -66,12 +69,22 @@ jobs:
           grep -H PASS *.check
           # Allow following grep to fail if no URL
           grep -H -e "# of nets with routing errors[. :]\+0" *.check.log || ${{ secrets.REPORT_ROUTE_STATUS_URL == '' }}
+          # Check no multiple sources, no stubs
+          ! grep "UserWarning: Found [0-9]\+ sources" *.wirelength
+          ! grep "UserWarning: Found [0-9]\+ stubs" *.wirelength
+          # Check wirelength was computed
+          grep "^Wirelength: [1-9][0-9]*" *.wirelength
       - name: Verify fail (nxroute-poc)
         if: matrix.router == 'nxroute-poc'
         run: |
           grep -H FAIL *.check
           # Allow following grep to fail if no URL
           grep -H -e "# of nets with routing errors[. :]\+[1-9]" -e "# of unrouted nets[. :]\+[1-9]" *.check.log || ${{ secrets.REPORT_ROUTE_STATUS_URL == '' }}
+          # Check no multiple sources, but expect stubs
+          ! grep "UserWarning: Found [0-9]\+ sources" *.wirelength
+          grep "UserWarning: Found [0-9]\+ stubs" *.wirelength || ${{ matrix.benchmark == 'koios_dla_like_large' }}
+          # Allow wirelength computation to fail since nxroute may not have routed anything or wirelength_analyzer was not run
+          grep "^Wirelength: [1-9][0-9]*" *.wirelength || true
       - uses: actions/upload-artifact@v3
         if: always()
         with:
@@ -79,6 +92,7 @@ jobs:
           path: |
            *.log
            *.check
+           *.wirelength
       - uses: actions/upload-artifact@v3
         if: always()
         with:
