Fix make.yml
Signed-off-by: Eddie Hung <eddie.hung@amd.com>

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -69,19 +69,22 @@ jobs:
           grep -H PASS *.check
           # Allow following grep to fail if no URL
           grep -H -e "# of nets with routing errors[. :]\+0" *.check.log || ${{ secrets.REPORT_ROUTE_STATUS_URL == '' }}
+          # Check no multiple sources, no stubs
+          ! grep "UserWarning: Found [0-9]+ sources"
+          ! grep "UserWarning: Found [0-9]+ stubs"
+          # Check wirelength was computed
+          grep "^Wirelength: [1-9][0-9]*" *.wirelength
       - name: Verify fail (nxroute-poc)
         if: matrix.router == 'nxroute-poc'
         run: |
           grep -H FAIL *.check
           # Allow following grep to fail if no URL
           grep -H -e "# of nets with routing errors[. :]\+[1-9]" -e "# of unrouted nets[. :]\+[1-9]" *.check.log || ${{ secrets.REPORT_ROUTE_STATUS_URL == '' }}
-      - name: Verify Critical-Path Wirelength
-        run: |
-          # Check no stubs, no multiple sources when not nxroute
-          grep "UserWarning: Found [0-9]+ sources" || ${{ matrix.router != 'nxroute-poc' }}
-          grep "UserWarning: Found [0-9]+ stubs" || ${{ matrix.router != 'nxroute-poc' }}
-          # Allow wirelength check to fail for benchmarks that cannot be analyzed
-          grep "^Wirelength: [1-9][0-9]*" *.wirelength || ${{ matrix.router == 'nxroute-poc' }}
+          # Check no multiple sources, but expec stubs
+          ! grep "UserWarning: Found [0-9]+ sources"
+          grep "UserWarning: Found [0-9]+ stubs"
+          # Allow wirelength computation to fail since nxroute may not have routed anything or wirelength_analyzer was not run
+          grep "^Wirelength: [1-9][0-9]*" *.wirelength || true
       - uses: actions/upload-artifact@v3
         if: always()
         with:
